### ISSUE TITLE
Update ReadTheDocs config to use the new build images

### ISSUE THREAD

**Issue by raucao** [remotestorage/remotestorage.js#1268]
It's now possible to ditch all the custom workarounds and environment and just specify a node.js version as well as npm packages to install, like so:

```yml
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
    nodejs: "16"
  jobs:
    post_install:
      - npm install -g jsdoc
```

https://github.com/readthedocs/readthedocs.org/issues/3069#issuecomment-1130049390

Hopefully this also fixes the builds being broken again (and more sustainably).
